name: trade_stats_accumulation
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_hooks: ^0.20.5
  google_mobile_ads: ^5.1.0
  flutter_riverpod: ^2.5.1
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.24
  riverpod_annotation: ^2.3.5
  riverpod_generator: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  envied: ^0.5.4+1
  path_provider: ^2.1.3
  file_picker: ^8.0.6
  slang_flutter: ^3.31.0
  slang: ^3.31.0
  google_fonts: ^6.2.1
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.5.1
  intl: ^0.19.0
  url_launcher: ^6.3.0
  uuid: ^4.4.2
  image_picker: ^1.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.5.2
  flutter_lints: ^3.0.0
  drift_dev: ^2.16.0
  build_runner: ^2.4.9
  envied_generator: ^0.5.3 # undefined
  slang_build_runner: ^3.30.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/images/no_image.png



flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/classifier.png"
  min_sdk_android: 21 # android min sdk min:16, default 21